## YAML Template.
all:
  recaptcha:
    enabled: false
  sfForkedApply:
    applyForm: sfApplyApplyForm
    resetForm: sfApplyResetForm
    resetRequestForm: sfApplyResetRequestForm
    settingsForm: sfApplySettingsForm
    editEmailForm: sfApplyEditEmailForm
    mail_editable: false
    confirmation:
      reset: true
      apply: true
      email: true
    routes:
      apply: /user/new
      reset: /user/password-reset
      resetRequest: /user/reset-request
      resetCancel: /user/reset-cancel
      validate: /user/confirm/:validate
      settings: /user/settings
